#!/bin/bash

FILE_PATH="${TRIM_APPDEST}/docker/docker-compose.yaml"

is_docker_running() {
    local docker_name=""
    if [ -f "${FILE_PATH}" ]; then
        docker_name="$(grep 'container_name' "${FILE_PATH}" | awk -F ':' '{print $2}' | xargs)"
    fi

    if [ -n "${docker_name}" ]; then
        docker inspect "${docker_name}" | grep -q '"Status": "running",' || return 1
        return 0
    fi

    return 1
}

case "$1" in
    start|stop) exit 0 ;;
    status) is_docker_running && exit 0 || exit 3 ;;
    *) exit 1 ;;
esac
